### ISSUE TITLE
Feature request: Add support for GraphQL schema file

### ISSUE THREAD

**Issue by fgoulet** [rafaelrenanpacheco/darcula-theme#27]
Support for GraphQL schema file (.graphql)  would be awesome

Thanks

**Comment by rafaelrenanpacheco** [comment]
Added GraphQL support on 1.18 :tada: 

It will require this extension to identify the language tokens because it is not native on vscode:

![image](https://github.com/user-attachments/assets/6e2df947-e0ee-4ec5-a207-d69fe2853162)

https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql-syntax
